podengo-project/idmsvc-frontend

src/Components/DomainList/DomainList.tsx

The "Status" column had a FIXME asking what is it for.  For now, there is nothing useful we can show there.  So remove the column.
Result:

Remove the Status column from list view

---

src/Routes/WizardPage/WizardPage.tsx

If the user steps back to the token page, settings they provided in the later pages of wizard are forgotten.
Avoid this by updating `onVerify` to return early if it detects that the registered state is already `'completed'`.  This avoid overwriting the domain in the wizard state with the "pristine" domain data from the `VerifyRegistry` component.

HMS-2151 fix: remember settings on step-back to token page

---

src/Routes/WizardPage/WizardPage.tsx

The default "title" field comes from the domain record (i.e. whatever ipa-hcc defaults it to).  But the wizard does not enable "Next" on the Service Details page until `onChangeTitle` fires.  In other words, the user *must* change the value before they can proceed.
It should be possible to accept the default.  Extract "data is OK to proceed" behaviour to a new function `onUserInputChange`.  Call this function from `onChangeTitle`, and *also* from `onVerify` when the domain data is first received.
As a result, the Next button on the Service Details page should be enabled immediately, allowing the user to accept the defaults.

HMS-2151 fix: make it possible to accept defaults

---

src/Components/DomainList/DomainList.tsx

Implement the enable/disable in the list view.  This implements the backend interaction and UI state update, but does NOT yet implement the "This will do X.  Are you sure?" interstitial dialogs.  That will be dealt with later (perhaps deferred until after the e2e demo milestone).
**Demo recording**:
[2023-10-13_19-17-44.webm](https://github.com/podengo-project/idmsvc-frontend/assets/2331938/26ff4fbd-e2b2-453b-87b4-93657ac98282)

HMS-2597 implement enable/disable in list view

---

src/Routes/WizardPage/Components/PageReview/PageReview.tsx
src/Routes/WizardPage/Components/PageServiceDetails/PageServiceDetails.tsx

Fixes https://issues.redhat.com/browse/HMS-2906

HMS-2906 update title/description microcopy in wizard

---

README.md
docs/04-context.md
src/AppContext.tsx
src/AppEntry.tsx
src/Components/DomainList/DomainList.tsx
src/Routes.tsx
src/Routes/DefaultPage/DefaultPage.tsx
src/Routes/DetailPage/Components/DetailGeneral/DetailGeneral.test.tsx
src/Routes/DetailPage/Components/DetailGeneral/DetailGeneral.tsx
src/Routes/DetailPage/Components/DetailServers/DetailServers.test.tsx
src/Routes/DetailPage/Components/DetailServers/DetailServers.tsx
src/Routes/DetailPage/Components/FilterField/filter-field.tsx
src/Routes/DetailPage/DetailPage.scss
src/Routes/DetailPage/DetailPage.tsx
src/Routes/WizardPage/Components/PagePreparation/PagePreparation.tsx
src/Routes/WizardPage/WizardPage.tsx

Add the detail view to show a general view and the list of servers that belongs to the selected domain.
The detail view allow to edit the **title**, **description** and **auto join on launch** feature, and delete the current domain.
TODO

HMS-1623 feat: add detail page

---

deploy/frontend.yaml

Update the Frontend resource to allow deploy by: `bonfire deploy --frontends idmsvc`; this change
cover the first acceptance criteria.
> The changes cannot be seen until frontend.yaml is merged, because the image is referenced as malformed image TBD:$(IMAGE_TAG), because bonfire read the frontend.yaml from the **main** branch.

HMS-2678 feat: frontend deploy resource

---

src/Components/DomainList/DomainList.tsx
src/Routes/DefaultPage/DefaultPage.tsx
src/Routes/DetailPage/Components/DetailGeneral/DetailGeneral.tsx
src/Routes/DetailPage/Components/DetailServers/DetailServers.tsx
src/Routes/DetailPage/DetailPage.tsx
src/Routes/WizardPage/Components/PagePreparation/PagePreparation.tsx
src/Routes/WizardPage/Components/PageReview/PageReview.tsx
src/Routes/WizardPage/Components/PageServiceDetails/PageServiceDetails.tsx
src/Routes/WizardPage/Components/PageServiceRegistration/PageServiceRegistration.tsx
src/Routes/WizardPage/Components/VerifyRegistry/VerifyRegistry.tsx
src/Routes/WizardPage/WizardPage.tsx

This add the **ouiaid** attribute at all the considered places so the selection of the components does not depends on the xpath or dom structure of the page.
General naming used:
`<Type><Location><Name>`
Where type so far are used the below:
* `Button*` when the component represent a button or item menu where to do click.
* `Link*` for components represented as a link where we can do click.
* `Text*` for components that accept text input or represent some label or static text.
Location represent the page, modal dialog, or component where it is contained.
Name is the name we assign to select the component.
All together represent the name to be used to select the component.

HMS-3432 feat: add ouiaid attribute

---

scripts/sh/search-ouia-compliant.sh
src/Components/DomainList/DomainList.tsx
src/Routes/DefaultPage/DefaultPage.tsx
src/Routes/DetailPage/Components/FilterField/filter-field.tsx
src/Routes/DetailPage/DetailPage.tsx
src/Routes/WizardPage/Components/PagePreparation/PagePreparation.tsx
src/Routes/WizardPage/Components/PageReview/PageReview.tsx
src/Routes/WizardPage/Components/PageServiceDetails/PageServiceDetails.tsx
src/Routes/WizardPage/Components/PageServiceRegistration/PageServiceRegistration.tsx

This change extend the initial ouiaId to cover the compliant components.
This change add a script (not perfect but enough) to do a quick search for the components on the frontend side for the compliant components.
The new name mapping for the type will be the below (copied from the script):
```raw
opts+=(-e \<Alert)             # Alert
opts+=(-e \<Breadcrumb)        # Breadcrumb
opts+=(-e \<Button)            # Button|Link
opts+=(-e \<Card)              # Card
opts+=(-e \<Checkbox)          # Checkbox
opts+=(-e \<Chip)              # Chip
opts+=(-e \<Dropdown)          # Dropdown
opts+=(-e \<DropdownItem)      # Dropitem
opts+=(-e \<FormSelect)        # Select
opts+=(-e \<Menu)              # Menu
opts+=(-e \<Modal)             # Modal
opts+=(-e \<Navigation)        # Nav
opts+=(-e …
```

feat(HMS-3574): add additional ouiaId

---

build/package/Dockerfile

Commit c854f2f52dc8c4c2455d46bf1416170d69db4b8a broke build process:
```
ERROR: failed to solve: failed to compute cache key: failed to calculate
checksum of ref ji869wphngyfym4bml6014fnn::rdlrmumtn45cgenzunvxem3ds:
"/dist": not found
```

fix(HMS-3414): Create directories in Containerfile

---

src/Components/DomainList/DomainList.tsx
src/Routes/WizardPage/Components/PageReview/PageReview.tsx

Distinguish domains with same name by adding a UUID column to the domain list.  This change assists test automation, in addition to possibly helping confused users (although we do not think this scenario will be common in real world use).
Fixes: https://issues.redhat.com/browse/HMS-3595
Screenshot of result:

HMS-3595: add UUID column to domain list

---

.dockerignore

'dist/' ignored at .dockerignore file was
evoking the directory not being copied.

fix: frontend container build

---

src/AppContext.tsx
src/Components/DomainList/DomainList.tsx
src/Routes/DefaultPage/DefaultPage.tsx

When a new domain was registered, the table was not being refreshed properly, requiring a manual refresh.
This change fix some situation with the application context that was evoking this behavior.

fix(HMS-3784): fix registered domains table refresh

---

src/Api/api.ts

Update the api client to be aligned with
https://github.com/podengo-project/idmsvc-api/pull/17

api: update generated api client

---

src/Components/AutoJoinChangeConfirmDialog/AutoJoinChangeConfirmDialog.scss
src/Components/AutoJoinChangeConfirmDialog/AutoJoinChangeConfirmDialog.test.tsx
src/Components/AutoJoinChangeConfirmDialog/AutoJoinChangeConfirmDialog.tsx
src/Components/DomainList/DomainList.tsx

A confirmation dialog is now opened on enable/disable action of domain auto-join in domains list.
On "OK" the change of domain auto-join is triggered. On cancel, the dialog is closed and nothing is done.

feat(HMS-2995): auto-join change confirmation dialog

---

.dockerignore

Add default known directories to be ignored on `.dockerignore` that could have sensible information.
`.docker`, `.podman` and `.kube`.
`*.log`

feat(HMS-3914): harden Dockerfile

---

src/Components/ConfirmDeleteDomain/ConfirmDeleteDomain.scss
src/Components/ConfirmDeleteDomain/ConfirmDeleteDomain.test.tsx
src/Components/ConfirmDeleteDomain/ConfirmDeleteDomain.tsx
src/Components/DomainList/DomainList.tsx
src/Routes/DetailPage/DetailPage.tsx

This change introduce the delete confirmation modal
dialog.
This dialog will show up when we click on the kebab
menu of the list domains view to delete the item, or
when we click on the kebab menu from the detail view
of the domain to delete the domain that is being
displayed.
In both cases, the deletion confirmation modal is
showed up, and when we press Delete button the
item is eventually deleted from the database.
Making click on the modal cross icon or cancel link
will dismiss the deletion confirmation modal with
no effect on the data stored.

feat(HMS-2994): delete domain confirmation

---

src/Routes/DetailPage/Components/DetailGeneral/DetailGeneral.tsx

**fix(HMS-4020): remove or improve help tooltips on details page**
Help tooltips were remove or improved so that there is no
tooltip with the same text as label.
**fix(HMS-4022): remove Certificate authority field from details page**
As it currently doesn't work and it is better to not have it than have
it broken.
Should be brought back in https://issues.redhat.com/browse/HMS-3002
Note: together as HMS-4022 is sort of part of HMS-4020 and separately they could conflict.

fix(HMS-4020): remove or improve help tooltips on details page

---

src/AppContext.tsx
src/Components/DomainList/DomainList.tsx
src/Routes/DefaultPage/DefaultPage.tsx
src/Routes/DetailPage/DetailPage.tsx
src/Routes/WizardPage/Components/PagePreparation/PagePreparation.tsx

**fix(HMS-4023): paging and reduce number of API requests**
Before, to load data for list page the UI did:
- 2x `domains?offest=0&limit=10` call
- a `readDomain` call for each returned domain
I.e. max 22 calls if the account has 10+ domains or
4 calls with a single domain.
Another issue was that the order of displayed domains was not stable.
Domains were added to appContext domain in order of finishing
asynchronous request. Thus it changed on each refresh.
Paging did not work as setting page and perPage was not propagated
well to the API call.
Now there is only single `domains?offset=$offset&limit=$pageSize` call
as this call returns all the data required for list page.
AppContext was extended to tracked results from `readDomain` and from
`domains` call separately. But `updateDomain`, …

fix(HMS-4023): paging and reduce number of API requests

---

src/App.tsx
src/Components/DomainList/DomainList.tsx
src/Hooks/useNotification.tsx
src/Routes/DetailPage/Components/DetailGeneral/DetailGeneral.tsx
src/Routes/DetailPage/DetailPage.tsx
src/Routes/DetailPage/detailNotifications.tsx

This PR implements bit more than HMS-2998 says, but in the end it's all about notifying edits of identity domains.
**refactor: useNotification hook**
Add an utility hook which provides easy-to use methods for displaying
notifications via `<NotificationsPortal />`.
Prep for: HMS-2997, HMS-2998
**feat(HMS-2998): domain edit notifications**
Add notifications for reporting success or error when domain description
or title are edited.
**fix: missing aria-title attributes in domain edit**
The missing attrs were reported in browser console. The UI is also more
accessible with them.
**feat: domain deletion notifications**
Show notification on successful or failed deletion of domain.
Improves UX.
**feat: domain auto-join change notifications**
Show notification on successful or failed change of …

feat(HMS-2998): notifications for edit / delete / change auto-join

---

src/Hooks/useNotification.tsx
src/Routes/WizardPage/WizardPage.tsx

Added notifications for cancelling and finishing a wizard.
The notification for cancel is a bit different then drafted in
HMS-2997 as the cancellation process is removing the registered
domain so in most cases it should end with the same result.
Rebased on top of https://github.com/podengo-project/idmsvc-frontend/pull/55 
Demo: https://drive.google.com/file/d/1wj6n70VCWuHjensaz_JqM6hh6uze5BE8/view?usp=drive_link
In the demo we can see that the notifications did not disappear in some cases.  I think this is connected with the way how the notification middleware/redux store is registered + navigation between pages. But I don't have a fix for it yet. Commit https://github.com/podengo-project/idmsvc-frontend/commit/463f9a82305d9af43d27851d34ed3074484a7aa6 had some possitive effect in pr 55 …

feat(HMS-2997): wizard notifications

---

src/App.tsx
src/AppEntry.tsx
src/Routes/WizardPage/WizardPage.tsx
src/store/index.ts

**fix: redux store configuration**
Adjust the configuration to run store initialization and reducer
registration only once on one place.
**fix(HMS-4059): notifications navigation issues**
Notifications stopped working well when using wizard. The issue
seems to be that `useSelector` hook, that is used in `NotificationsPortal`,
stopped reacting to state changes and thus the notifications "stopped"
working well.
The situation looks to be gone after removing the lazy load of wizard pages.
This also improves a bit perceived responsiveness when already in the app
as the wizard pages are displayed right after navigating to them as there
is no load.
Removing the load should also be OK from code splitting perspective as
the pages are not big and thus could be part of the main app.

fix(HMS-4059): notifications navigation issues

---

src/Routes/WizardPage/WizardPage.tsx

When the domain is registered on the backend, it is created with autoenrollment disabled (https://github.com/podengo-project/idmsvc-backend/pull/198/files).
When the verification happens on the frontend, the returned value is false, but we want to set by default for the UI enabled. This change is not effective until the user finish the wizard and click the Finish button, and at that time the PATCH /domains/:domain_id is sent and whatever that the user decided (leave disabled, or enabled) is then set on the backend side.
DRAFT: until it is reviewed the ipa-hcc pipeline don't get broken by: https://github.com/podengo-project/idmsvc-backend/pull/198/files

fix(HMS-4061): fix auto enrollment

---

package.json

To prevent introduction of new TypeScript lint warnings in the codebase.

ci(HMS-4082): fail eslint on warnings

---

package.json

Which calls `jest --watch`. This is useful for development of unit tests. On save of modified file, unit tests related to the changed file are executed.

test: add npm run test-watch target

---

src/Components/AutoJoinChangeConfirmDialog/AutoJoinChangeConfirmDialog.tsx
src/Components/ConfirmDeleteDomain/ConfirmDeleteDomain.tsx
src/Routes/DefaultPage/DefaultPage.tsx
src/Routes/WizardPage/Components/PagePreparation/PagePreparation.tsx
src/Routes/WizardPage/Components/PageServiceRegistration/PageServiceRegistration.tsx

Update some UI text for correctness or clarity.

HMS-4126: update some strings

---

package-lock.json
package.json

Soft bump react-router-dom to 6.23.1 and remove @types/react-router as they are obsolete and should be part of react-router-dom.

build(HMS-4081): bump react-router-dom

---

src/Components/ConfirmDeleteDomain/ConfirmDeleteDomain.test.tsx
src/Components/ConfirmDeleteDomain/ConfirmDeleteDomain.tsx

Add confirmation checkbox that enables delete button to warn user that the action cannot be undone.
In unit test, some jest calls were replaced by newer variants as the older were deprecated.

feat(HMS-4156): confirmation checkbox in delete domain confirm modal

---

src/Routes/WizardPage/WizardPage.tsx

Refactoring done in 45af0c949f35004e780625b323f187066ade8352 in context of HMS-4080 introduced a regression where disabling/enabling of "next" step in wizard stopped working. Thus user could navigate from step 2 to 3 without registering the domain. This lead to further issues.
This commit is fixing the issue - bringing the old behavior back.

fix(HMS-4080): next step enablement in wizard

---

README.md
src/AppContext.tsx
src/Hooks/useIdmPermissions.tsx

This change is build on top of #64.
This change provide the specific hook to check
the idmsvc permissions so this can be used
broadly on the whole UI.

feat(HMS-2721): integrate check permissions

---

src/Components/DomainList/DomainList.tsx
src/Routes/DefaultPage/DefaultPage.tsx
src/Routes/DetailPage/Components/DetailGeneral/DetailGeneral.tsx
src/Routes/DetailPage/DetailPage.tsx

This change add more granularity to the RBAC integration
in the UI by enabling/disabling in a selective way, the
related controls, depending on the current permissions
when the user logged in.
https://issues.redhat.com/browse/HMS-4129

feat(HMS-4129): support rbac on UI controls

---

jest.config.js
src/Components/NoPermissions/NoPermissions.test.tsx
src/Components/NoPermissions/NoPermissions.tsx
src/Routes.tsx
src/Routes/DefaultPage/DefaultPage.tsx
src/Routes/DetailPage/DetailPage.tsx
src/Routes/WizardPage/WizardPage.tsx

When accessing a page where a user doesn't have neccessary permissions for the page, the user was previously redirected to a "NoPermissions" page. This is changing it in a way that user is not longer redirected but the NoPermission content is used for the current page instead of the current content.
Thus it won't change page URL and allows to refresh the page to get the content if users permissions change.
https://issues.redhat.com/browse/HMS-4253

fix(HMS-4253): do not change url when missing RBAC permissions

---

src/Routes/DetailPage/Components/DetailGeneral/DetailGeneral.tsx

So that "pencil" icons have the same color. Removes unnecessary class.

fix(HMS-4228): unify style of inline links on details page

---

src/Components/DomainList/DomainList.tsx

Sorrting of domains in domains list did not work as the function which was returning rows for sorting did not return one column thus the index for "domain autojoin" returned undefined value for all rows.
Returning the same amount of values as columns fixes the issue.
https://issues.redhat.com/browse/HMS-4217

fix(HMS-4217): sorting of domains

---

package.json

When running `make run` or `npm run start`, developer has to manually specify HCC environment, e.g. `stage`, and UI environment, e.g., `beta`.
This is "annoying" when the values are always the same, which atm are. Thus introducing a `make run start-beta` which defines these two params and thus it starts serving with single command.

build: `npm run start-beta` target

---

src/Routes/DefaultPage/DefaultPage.tsx
src/Routes/DetailPage/DetailPage.tsx

Improving the loading indicators UX with skeleton.
When loading RBAC or first load of domains, still show spinner as it is not known what will be displayed.
When some domains were loaded, use skeleton table instead of spinner when refreshing the domains table.
In details page, use skeleton as place holders for the form and title.
Also fixes a bug in pagination, by removing offset, it then shows correct Y in showing X - Y out of Y + adding a bit of margin between pagination and the table.
https://issues.redhat.com/browse/HMS-4265

feat(HMS-4265): skeleton as loading indicator

---

package.json
scripts/mk/crc-frontend.mk
scripts/mk/variables.mk

This change move the options to launch with no prompts to the make rules.
By default use the options commonly used for development but could be customized.
Inspired by: https://github.com/podengo-project/idmsvc-frontend/pull/77

build: launch with no prompts from make rule

---

src/Routes/DetailPage/Components/DetailGeneral/DetailGeneral.tsx

Empty domain title causes issues when navigating from domains table to detail.
This also reflects backend change where such request will end in "400 bad request".

fix(HMS-2979): do not allow to save emty domain title

---

src/Routes/DefaultPage/DefaultPage.tsx
src/Routes/WizardPage/Components/PagePreparation/PagePreparation.tsx
src/Routes/WizardPage/WizardPage.tsx

This change remove links that will exist
in the future, to avoid confusion for the
end user.
Specifically:
- It removes the 'learning more ...' link at the header of the empty page and wizard.
- It removes the 'pre-requisites' link in the first page of the wizard.

fix(HMS-4377): no display links

---

config/bonfire.example.yaml
scripts/mk/variables.mk

Instead of stage:beta which no longer works.
Also fixing a typo in ephemeral deployment template.

chore: stage:stable as default fec env

---

config/bonfire.example.yaml

Debug level and source code location logging was set for idmsvc-backend so that the template is more usable out of the box. The default was "warn". Thus it is easier to investigate requests done to the API.
Source code location logging is now consistent with idmsvc-backend repo.
Also fixes incorrect GitHub namesapce.

chore(HMS-4521): ephemeral logging - debug level and source location

---

package-lock.json

axios-1.7.4 fixes an SSRF vulnerability.  Bump deps to this version. See also references:
- https://jeffhacks.com/advisories/2024/06/24/CVE-2024-39338.html
- https://github.com/axios/axios/releases/tag/v1.7.4
- https://github.com/advisories/GHSA-8hc4-vh64-cxmj

deps: bump axios to v1.7.4 (fixes CVE-2024-39338)

---

README.md
build/package/Caddyfile
build/package/Dockerfile
package-lock.json
package.json
scripts/mk/crc-frontend.mk
src/Components/NoPermissions/NoPermissions.test.tsx
src/Components/NoPermissions/NoPermissions.tsx

**fix(HMS-4621): remove beta/preview URL prefixes**
This PR aims to address ADR-044 - removal of /preview URL.
Not all references to /beta or /preview were removed as e.g.
emhemeral environment is still using it.
**chore(HMS-4621): update frontend-components-config to ^6.2.8**
As the newer version addresses removal of /preview URL prefixes.

fix(HMS-4621): remove beta/preview URL prefixespreview

---

src/Routes/WizardPage/Components/PagePreparation/PagePreparation.tsx
src/Routes/WizardPage/Components/PageServiceRegistration/PageServiceRegistration.tsx
src/Routes/WizardPage/Components/VerifyRegistry/VerifyRegistry.tsx
src/Routes/WizardPage/WizardPage.tsx

- Wizard Page 1 - Preparation: Remove paragraph about the pre-requisites and package verification, and leave only the 2nd and 3rd paragraph indicating the package to be installed. Remove the link about steps to install the server packages. Remove the link about pre-requisites. The link in the alert point out to documentation about "Deploying and managing RHEL systems in hybrid clouds".
- Wizard page 2 - Registration: Remove the link in the warning alert.
- The verify component remove the link to troubleshooting, when is in error state.
- The cancel wizard registration modal remove the link intended to provide information about deleting an ipa server, as the process is more related with the registration with the hcc.
Credits on: @ragevou
TODO
https://issues.redhat.com/browse/HMS-2141

fix(HMS-2141): update link and contents

---

requirements-dev.txt

This change bump bonfire to 5.11.1 which add a workaround to let deploy in dev cluster.

bump: crc-bonfire to 5.11.1

---

.tekton/idmsvc-frontend-push.yaml

The EC require rpms-signature-scan; this change uncomment the task, and update it aligned with the current definition that we can find in the idmsvc-backend component.
https://issues.redhat.com/browse/HMS-5181

fix(HMS-5181): uncomment rpms-signature-scan
